baseURL = "https://noahsec.pro"
languageCode = "en-us"
title = "Security Portfolio"
theme = "anatole"

#summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = ""

[params]
  title = "NoahSec"
  author = "Noah"
  description = """
  Noah's security portfolio 
  and accomplishments.
  """
  profilePicture = "images/profile.png"
  copyright = "Noah Aronov 2023-{{ YEAR }}"
  reversepagetitle = true
  #mainSections = [""]

    [[params.socialIcons]]
      icon = "fab fa-linkedin"
      title = "LinkedIn"
      url = "https://linkedin.com"

    [[params.socialIcons]]
      icon = "fas fa-envelope"
      title = "e-mail"
      url = "mailto:noah@noahsec.pro"

[menu]

  [[menu.main]]
    name = "About"
    identifier = "about"
    weight = 100
    url = "/"

  [[menu.main]]
    name = "Portfolio"
    identifier = "portfolio"
    weight = 200
    url = "/portfolio/"
