baseURL = "https://noahsec.pro"
languageCode = "en-us"
title = "Security Portfolio"
theme = "anatole"

#summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = ""

[params]
  title = "NoahSec"
  author = "Noah"
  description = """
  Noah's security portfolio 
  and accomplishments.
  """
  profilePicture = "images/profile.jpg"
  copyright = "Noah Aronov 2023-{{ YEAR }}"
  reversepagetitle = true
  mainSections = [""]
  hidesidebar = true
    
    [[params.socialIcons]]
      icon = "fab fa-github"
      title = "GitHub"
      url = "https://github.com/NoahAronov"

    [[params.socialIcons]]
      icon = "fab fa-linkedin"
      title = "LinkedIn"
      url = "https://linkedin.com/in/noahsec/"

    [[params.socialIcons]]
      icon = "fab fa-medium"
      title = "Medium"
      url = "https://medium.com/@noahsec"

    [[params.socialIcons]]
      icon = "fab fa-youtube"
      title = "YouTube"
      url = "https://youtube.com/@noahsec"

    [[params.socialIcons]]
      icon = "fas fa-envelope"
      title = "e-mail"
      url = "mailto:noah@noahsec.pro"

[menu]

  [[menu.main]]
    name = "About"
    identifier = "about"
    weight = 100
    url = "/"

  [[menu.main]]
    name = "Portfolio"
    identifier = "projects"
    weight = 200

  [[menu.main]]
    name = "Home Lab & Projects"
    identifier = "portfolio"
    weight = 210
    url = "/portfolio/"
    parent = "projects"

  [[menu.main]]
    name = "Writing"
    identifier = "writing"
    weight = 220
    url = "/writing/"
    parent = "projects"

  [[menu.main]]
    name = "Presentations"
    identifier = "presentations"
    weight = 230
    url = "/presentations/"
    parent = "projects"

  [[menu.main]]
    name = "Education"
    identifier = "education"
    weight = 300

  [[menu.main]]
    name = "Academics"
    identifier = "academics"
    weight = 310
    url = "/academics/"
    parent = "education"

  [[menu.main]]
    name = "Certifications"
    identifier = "certifications"
    weight = 320
    url = "/certifications/"
    parent = "education"

  [[menu.main]]
    name = "Competitions"
    identifier = "competitions"
    weight = 330
    url = "/competitions/"
    parent = "education"

  [[menu.main]]
    name = "Honors"
    identifier = "honors"
    weight = 340
    url = "/honors/"
    parent = "education"  

  [[menu.main]]
    name = "Extra Courses"
    identifier = "courses"
    weight = 350
    url = "/courses/"
    parent = "education"

  [[menu.main]]
    name = "Research Areas"
    identifier = "research"
    weight = 360
    url = "/research/"
    parent = "education"

  [[menu.main]]
    name = "Profile"
    identifier = "profile"
    weight = 400

  [[menu.main]]
    name = "Experience"
    identifier = "experience"
    weight = 410
    url = "/experience/"
    parent = "profile"

  [[menu.main]]
    name = "Organizations"
    identifier = "organizations"
    weight = 420
    url = "/organizations/"
    parent = "profile"

  [[menu.main]]
    name = "Resume"
    identifier = "resume"
    weight = 430
    url = "/resume/"
    parent = "profile"