baseURL = 
languageCode = "en-us"
title = "NoahSec"
theme = "anatole"

#summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = ""