#title = "I'm Jane Doe"
#author = "Jane Doe"
#copyright = "2020-2021"
#description = "Call me Jane"
#profilePicture = "images/profile.jpg"
#keywords = ""
#favicon = "favicons/"
# example ["css/custom.css"]
#customCss = []
# example ["js/custom.js"]
#customJs = [] 
#mainSections = ["post"]
#images = ["images/site-feature-image.png"]
#doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
#contactFormReCaptcha = "your-site-key-here"
# Google Fonts
#googleFonts = ["Indie+Flower", "Roboto:ital,wght@0,100;0,400;0,700;1,400"]
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
#singleDateFormat = "2/1/2006"
#indexDateFormat = "2/1/2006"
#listDateFormat = "2/1/2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"
# relatedPosts = true
# numberOfRelatedPosts = 3

#reversepagetitle = true # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'

# hidesidebar = true

title = "test title"
author = "test author"
description = "test desc"
profilePicture = "images/profile.png"
copyright = "2023-{{ YEAR }}"

[socialIcons]
icon = "fab fa-linkedin"
title = "LinkedIn"
url = "https://linkedin.com"

[socialIcons]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:noah@noahsec.pro"
